
import Head from 'next/head'
import Link from 'next/link'
import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'


type MainLayoutProps = {
  children: React.ReactNode;
}


export const MainLayout = ( props: MainLayoutProps ) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Contact-Ruth APP</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar />
    
          <main className={styles.main}>
            { props.children }
          </main>
    
        
        </div>
      )
}
